import { ChecklistTemplate } from "./types";

export const checklistTemplates: ChecklistTemplate[] = [
  {
    id: "tmpl_global_budget_planning",
    key: "global-budget-planning",
    title: "Confirm budget ranges and owners",
    description: "Align on budget envelope, who approves payments, and constraints.",
    type: "task",
    category: "budget",
    timeBucket: "6_plus_months",
    priority: "high",
  },
  {
    id: "tmpl_global_guest_estimates",
    key: "global-guest-estimates",
    title: "Estimate guest counts per event",
    description: "Rough counts to size venues and catering.",
    type: "task",
    category: "guests",
    timeBucket: "6_plus_months",
  },
  {
    id: "tmpl_global_legal_documents",
    key: "global-legal-documents",
    title: "Collect ID, birth certificates, affidavits",
    type: "item",
    category: "documents_legal",
    timeBucket: "3_6_months",
    priority: "high",
  },
  {
    id: "tmpl_event_poruwaceremony_officiant",
    key: "poruwa-officiant",
    title: "Confirm Poruwa officiant and drummers",
    type: "task",
    category: "rituals",
    timeBucket: "3_6_months",
    eventTypes: ["poruwa"],
  },
  {
    id: "tmpl_event_reception_photography",
    key: "reception-photography",
    title: "Reception photography shot list",
    type: "task",
    category: "photography",
    timeBucket: "1_3_months",
    eventTypes: ["reception"],
  },
  {
    id: "tmpl_event_reception_transport",
    key: "reception-transport",
    title: "Arrange transport for reception party",
    type: "task",
    category: "transport",
    timeBucket: "1_month",
    eventTypes: ["reception"],
  },
  {
    id: "tmpl_jewelry_thali_gold",
    key: "jewelry-thali-gold",
    title: "Purchase gold for Thali/Thirumangalyam",
    type: "item",
    category: "jewelry",
    timeBucket: "3_6_months",
    isJewelry: true,
    priority: "high",
    jewelryType: "necklace",
    defaultOwner: "bride-family",
    weddingTypes: ["hindu", "buddhist", "mixed"],
    ritualKeys: ["thali-ceremony", "poruwa-main"],
  },
  {
    id: "tmpl_jewelry_rental_return",
    key: "jewelry-rental-return",
    title: "Schedule jewelry rental pickup and return",
    type: "task",
    category: "jewelry",
    timeBucket: "1_month",
    isJewelry: true,
    jewelryType: "rental-set",
    defaultOwner: "vendor",
  },
  {
    id: "tmpl_ritual_poruwamain_items",
    key: "poruwa-main-items",
    title: "Prepare Poruwa ritual items (oil lamp, sheaves, tray)",
    type: "item",
    category: "rituals",
    timeBucket: "1_month",
    ritualKeys: ["poruwa-main"],
    eventTypes: ["poruwa"],
  },
  {
    id: "tmpl_ritual_thali_items",
    key: "thali-ceremony-items",
    title: "Prepare Thali ceremony items (chain, flowers, tray)",
    type: "item",
    category: "rituals",
    timeBucket: "1_week",
    ritualKeys: ["thali-ceremony"],
    eventTypes: ["poruwa", "nikah", "hindu_main"],
  },
  {
    id: "tmpl_after_post_wedding_returns",
    key: "post-wedding-returns",
    title: "Return rentals and clear deposits",
    type: "task",
    category: "post_wedding",
    timeBucket: "after",
  },
  {
    id: "tmpl_jewelry_homecoming_set",
    key: "jewelry-homecoming-set",
    title: "Prepare homecoming jewelry set",
    description: "Match homecoming outfit; confirm custody and logistics.",
    type: "item",
    category: "jewelry",
    timeBucket: "1_month",
    isJewelry: true,
    jewelryType: "set",
    defaultOwner: "bride-family",
    eventTypes: ["homecoming"],
  },
  {
    id: "tmpl_jewelry_reception_set",
    key: "jewelry-reception-set",
    title: "Reception jewelry set ready",
    description: "Ensure reception set is packed and custody clarified.",
    type: "item",
    category: "jewelry",
    timeBucket: "1_week",
    isJewelry: true,
    jewelryType: "set",
    defaultOwner: "couple",
    eventTypes: ["reception"],
  },
  {
    id: "tmpl_jewelry_church_bridal",
    key: "jewelry-church-bridal",
    title: "Church ceremony bridal jewelry",
    type: "item",
    category: "jewelry",
    timeBucket: "1_month",
    isJewelry: true,
    jewelryType: "set",
    defaultOwner: "bride-family",
    weddingTypes: ["christian", "mixed"],
    eventTypes: ["church"],
  },
  {
    id: "tmpl_jewelry_mehendi_light",
    key: "jewelry-mehendi-light",
    title: "Mehendi light jewelry set",
    type: "item",
    category: "jewelry",
    timeBucket: "1_month",
    isJewelry: true,
    jewelryType: "light-set",
    defaultOwner: "bride-family",
    weddingTypes: ["hindu", "mixed"],
    eventTypes: ["mehendi", "haldi", "sangeet"],
  },
];
